name: Deliver Tokens To Consumer

on:
  push:
    paths:	
      - 'build/**'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_react_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Application
      uses: andstor/copycat-action@v3
      with:
        # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
        # Set the secret in the "src" repository
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        # This is the branch that has the code for this article
        src_branch: design-tokens
        src_path: build/scss/_variables.scss
        # This is the Destination branch
        dst_owner: c3-andrewkim
        dst_repo_name: token-consumer-example-repo
        dst_branch: main
        dst_path: tokens/_variables.scss
        username: c3-andrewkim
        email: andrew.kim@c3.ai
        commit_message: Update platform deliverable